Added kicking of players from a running mission
ciribob/DCS-SimpleSlotBlock pull request #1
Opened 2017-10-11 15:00 UTC by FlightControl-Master

Through the manipulation of the user flags, players can now also be kicked.
I also added a couple of additional variables that can be modified to disable / tweak the player kicking.

DCS as a bug in the multiplayer system. Unit:destroy() does not work in MP when a player seated from a client PC is destroyed on the server.

This development however, is better, as this allows also to block slots upon preference from the mission, not just kicking. So this has become a nice set of functions to use together with missions.

I hope this change will find its way in the community.

The MOOSE framework will make heavy use of this. For example in the AIRBASEPOLICE.
Speeding pilots on the runway will be kicked!

cheers,
Sven

2017-10-18 08:23 UTC, ciribob requested changes

2017-10-18 08:23 UTC, ciribob commented on SimpleSlotBlockGameGUI.lua
> +                ssb.rejectPlayer(playerID)
After this - I'd clear the flag after removing the user from the slot as for the particular behaviour I assume you dont want the slot disabled forever

2017-10-18 08:49 UTC, FlightControl-Master commented on SimpleSlotBlockGameGUI.lua
> +                ssb.rejectPlayer(playerID)
I have deliberately not done this because then the mission is in control.

2017-10-18 08:52 UTC, FlightControl-Master commented on SimpleSlotBlockGameGUI.lua
> +                ssb.rejectPlayer(playerID)
Thinking about it. I could add a flag to auto unblock... I'll do that. Thanks for suggestion. Ill update.

2017-10-19 08:09 UTC, FlightControl-Master commented
OK. I did the following:

1. Added method ssb.allowAircraftSlot(_playerID, _slotID) to allow an aircraft slot.
2. Added method ssb.setFlagValue(_flag, _number) to set a flag value.
3. Added a control variable ssb.kickReset = true -- The slot will be automatically reset to open, after kicking the player.
4. When a player gets kicked in mid flight, the slot will be automatically re-opened.
5. Reformatted the source to 2 indents. (auto format in eclipse)
6. Improved a bit on the documentation, added an Additions section.

2017-10-19 08:10 UTC, FlightControl-Master commented
The module is heavily tested, and will be used by the TAW competition event, which we are preparing.

2017-10-19 15:30 UTC, FlightControl-Master commented
On mission end, i am resetting some persistent variables ... prevTimeKick.
You can publish now.

2017-10-19 19:17 UTC, merged

2017-10-19 19:20 UTC, FlightControl-Master commented
Thank you!